---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"

  tasks: 
    - name: Display all variables/facts known for a host
      ansible.builtin.debug:
       msg: 
         - "Inventory Hostname: {{ inventory_hostname }}"
         - "Inventory VARs: {{ PKI_DIR }}"
      tags:
        - debug

    - name: Remove PKI directory
      ansible.builtin.file:
        path: "{{ PKI_DIR }}"
        state: absent
      tags:
        - cleanup

    - name: Remove the public key in the '{{ ssh_known_hosts_file }}'
      known_hosts:
        name: "{{ gcp_ip_address }}"
        path: "{{ ssh_known_hosts_file }}"
        state: absent
      tags:
        - cleanup

    - name: Remove inventory file
      ansible.builtin.file:
        path: "./inv"
        state: absent
      tags:
        - cleanup

