#cloud-config

# Update apt database on first boot (run 'apt-get update').
package_update: true

# Upgrade the instance on first boot
package_upgrade: true

# Downloads the vim package
packages:
  - htop
  - tree
  - nginx

