---
- hosts: all
  gather_facts: no
  tasks:
    - name: Display all variables/facts known for a host
      ansible.builtin.debug:
       msg: 
         - "Inventory Hostname: {{ inventory_hostname }}"
         - "Inventory Remote Host: {{ hostvars[inventory_hostname].ansible_host }}"
         - "Inventory VARs: {{ hostvars[inventory_hostname] }}"
