---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    ssh_known_hosts_command: "ssh-keyscan -T 10 -H"
    ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
    ssh_known_hosts: "{{ groups['all'] }}"

  tasks: 
    - name: Display all variables/facts known for a host
      ansible.builtin.debug:
       msg: 
         - "Inventory Hostname: {{ inventory_hostname }}"
         - "Inventory VARs: {{ PKI_DIR }}"
      tags:
        - debug

    - name: Create PKI directory
      ansible.builtin.file:
        path: "{{ PKI_DIR }}"
        state: directory
      tags:
        - pki

    ## Create CA
    - name: Generate CA private key
      community.crypto.openssl_privatekey:
        path: "{{ PKI_DIR }}/ca-key.pem"
      tags:
        - pki

    - name: Generate CA CSR
      community.crypto.openssl_csr:
        path: "{{ PKI_DIR }}/ca.csr"
        privatekey_path: "{{ PKI_DIR }}/ca-key.pem"
        basic_constraints: "CA:TRUE"
        basic_constraints_critical: True
        key_usage: 
          - cRLSign
          - keyCertSign
        key_usage_critical: True
        organizational_unit_name: "EVT Challenge"
        common_name: CA
      tags:
        - pki

    - name: Generate CA certificate
      community.crypto.x509_certificate:
        path: "{{ PKI_DIR }}/ca.pem"
        privatekey_path: "{{ PKI_DIR }}/ca-key.pem"
        csr_path: "{{ PKI_DIR }}/ca.csr"
        provider: selfsigned
      tags:
        - pki

    - name: Generate Web Server private key
      community.crypto.openssl_privatekey:
        path: "{{ PKI_DIR }}/server-key.pem"
      tags:
        - pki

    - name: Generate Web Server CSR
      community.crypto.openssl_csr:
        path: "{{ PKI_DIR }}/server.csr"
        privatekey_path: "{{ PKI_DIR }}/server-key.pem"
        basic_constraints: "CA:FALSE"
        basic_constraints_critical: True
        key_usage: 
          - digitalSignature
          - keyEncipherment
        key_usage_critical: True
        extended_key_usage: 
          - serverAuth
          - clientAuth
        common_name: "webserver"
        organization_name: "EVT Challenge"
        organizational_unit_name: "Unit"
        subject_alt_name: "IP:{{ gcp_ip_address }}"
      tags:
        - pki

    - name: Generate Web Server certificate
      community.crypto.x509_certificate:
        path: "{{ PKI_DIR }}/server.pem"
        csr_path: "{{ PKI_DIR }}/server.csr"
        ownca_path: "{{ PKI_DIR }}/ca.pem"
        ownca_privatekey_path: "{{ PKI_DIR }}/ca-key.pem"
        provider: ownca
      tags:
        - pki

    - name: Scan ssh public key from cloud VM
      shell: "ssh-keyscan -T 10 -H {{ gcp_ip_address }}"
      register: ssh_known_host_results
      ignore_errors: yes
      tags:
        - ssh

    - name: Add/update the public key in the '{{ ssh_known_hosts_file }}'
      ansible.builtin.known_hosts:
        name: "{{ gcp_ip_address }}"
        key: "{{ ssh_known_host_results.stdout }}"
        path: "{{ ssh_known_hosts_file }}"
        state: present
      tags:
        - ssh
      